name: Playwright Tests
on:
  push:
    branches: [main]
jobs:
  playwrighttests:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.37.1-focal
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run tests
        run: |
          echo "Start the shopping store application"
          chmod +x ./shopping-store-windows-386.exe &
          echo "Intall dependecies from lockfile"
          npm ci
          echo "Run playwright tests"
          npm run test:ci
